apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: default
spec:
  type: LoadBalancer  # Exposes pgAdmin over a Public IP
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
